### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by spongemook** [spromicky/StepSlider#39]
<img width="828" alt="CrashReport" src="https://user-images.githubusercontent.com/8064865/69070836-38911780-0a6c-11ea-8078-b4bab35cf50b.png">

**Comment by spromicky** [comment]
can you give more details? version, frequency etc.

**Comment by spongemook** [comment]
StepSlider Version : 1.3.0
Language : Swift 5
Crash Device : iPhone X (13.1.3)

**Comment by spromicky** [comment]
It was fixes in version 1.5.0. You should update to this version.

**Comment by CharlesSamuelDMonte** [comment]
The issue still exists. The crash occurs when you hold the thumb, and drag and release it fast, as if you're swiping, instead of slowly dragging it along. The issue seems to be occurring because oldPath gets deallocated. 

The crash is fixed when getting the value of _oldPath_ from a copy of __trackLayer_, instead of from __trackLayer_ itself.

```
CAShapeLayer * trackLayerCopy = [NSKeyedUnarchiver unarchiveObjectWithData:[NSKeyedArchiver archivedDataWithRootObject:_trackLayer]];
    CGPathRef oldPath   = trackLayerCopy.path;
```

 instead of 

`CGPathRef oldPath   = _trackLayer.path;`

**Comment by spongemook** [comment]
The same problem exists in 1.5.0.

**Comment by iVarunPatel** [comment]
@spongemook setting animation false worked for me.
